apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
- helm-longhorn.yaml
- ingress.yaml
- volume-snapshot.yaml
- https://github.com/kubernetes-csi/external-snapshotter/client/config/crd

patches:
- path: tracking-patch.yaml