apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: template
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ente-photos-config
  data:
  - secretKey: pgpass
    remoteRef:
      key: ente-photos-postgres
      property: password
  - secretKey: miniopass
    remoteRef:
      key: minio-ente-photos-user
      property: password

