apiVersion: v1
kind: Service
metadata:
  name: museum
spec:
  selector:
    matchLabels:
      app: ente
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "2112"
      port: 2112
      targetPort: 2112
