apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
  namespace: argocd
$patch: merge
spec:
  template:
    spec:
      containers:
        - livenessProbe: {}
            # failureThreshold: 3
            # periodSeconds: 10
            # successThreshold: 1
            # tcpSocket:
            #   port: 9001
            # timeoutSeconds: 1