apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
  namespace: argocd
$patch: replace
spec:
  template:
    spec:
      containers:
        - op: delete
          livenessProbe: {}