kind: Deployment
metadata:
  name: argocd-notifications-controller
  namespace: argocd
spec:
  template:
    spec:
      containers:
          $patch: replace
          livenessProbe: {}
            # failureThreshold: 3
            # periodSeconds: 10
            # successThreshold: 1
            # tcpSocket:
            #   port: 9001
            # timeoutSeconds: 1