apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghost-mail-config
  namespace: ghost-blog
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ghost-mail-config
    creationPolicy: Owner
  data:
  - secretKey: mail__transport
    remoteRef:
      key: kv/ghost-blog/config
      property: email_transport
  - secretKey: mail__from
    remoteRef:
      key: kv/ghost-blog/config
      property: email_from
  - secretKey: mail__options__service
    remoteRef:
      key: kv/ghost-blog/config
      property: email_service
  - secretKey: mail__options__host
    remoteRef:
      key: kv/ghost-blog/config
      property: email_host
  - secretKey: mail__options__port
    remoteRef:
      key: kv/ghost-blog/config
      property: email_port
  - secretKey: mail__options__auth__user
    remoteRef:
      key: kv/ghost-blog/config
      property: email_user
  - secretKey: mail__options__auth__pass
    remoteRef:
      key: kv/ghost-blog/config
      property: email_password