apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content
  namespace: ghost-blog
  labels:
    app: ghost-blog
    app.kubernetes.io/name: ghost-content
    app.kubernetes.io/instance: ghost-blog
    app.kubernetes.io/version: '5.92'
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: ghost-blog
spec:
  storageClassName: "longhorn"
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-mysql-pvc
  namespace: ghost-blog
  labels:
    app: ghost-mysql
    app.kubernetes.io/name: ghost-mysql-pvc
    app.kubernetes.io/instance: ghost-blog
    app.kubernetes.io/version: '5.92'
    app.kubernetes.io/component: database-storage
    app.kubernetes.io/part-of: ghost-blog
spec:
  storageClassName: "longhorn"
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
