apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actualbudget-oidc-client-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: actualbudget-oidc-client-secret
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: kv/actualbudget-oidc
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: kv/actualbudget-oidc
        property: client_secret
