apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: bolletjestrui
  name: bolletjestrui-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
