apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bolletjestrui-secrets
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: bolletjestrui-secrets
    creationPolicy: Owner
  data:
    - secretKey: site_password
      remoteRef:
        key: kv/bolletjestrui
        property: site_password
    - secretKey: admin_password
      remoteRef:
        key: kv/bolletjestrui
        property: admin_password
    - secretKey: key_secret
      remoteRef:
        key: kv/bolletjestrui
        property: key_secret
