apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: ''
    repoURL: https://charts.jetstack.io
    targetRevision: v1.15.3
    chart: cert-manager
    helm:
      parameters:
        - name: crds.enabled
          value: 'true'