apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator
  namespace: argocd
spec:
  destination:
    namespace: mariadb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: mariadb-operator
    repoURL: https://mariadb-operator.github.io/mariadb-operator
    targetRevision: 25.10.4
    helm:
      values: |
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
