apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mbgwp-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mbgwp
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 24.1.18
    chart: wordpress
    helm:
      values: |
        image:
          repository: bitnamilegacy/wordpress
        service:
          ## @param service.type WordPress service type
          ##
          type: ClusterIP
        ingress:
          enabled: true
          ingressClassName: nginx
          hostname: scoutingmbg.nl
          path: /
          annotations:
            cert-manager.io/cluster-issuer: prod-cluster-issuer
            nginx.ingress.kubernetes.io/proxy-body-size: 1G
          tls: true
          tlsWwwPrefix: false
          selfSigned: false
          extraHosts: 
            - name: www.scoutingmbg.nl
          extraPaths: []
          extraTls:
            - secretName:  letsencrypt-prod
              hosts:
                - scoutingmbg.nl
                - www.scoutingmbg.nl
          secrets: []
          extraRules: []

        persistence:
          ## @param persistence.enabled Enable persistence using Persistent Volume Claims
          ##
          enabled: true
          ## @param persistence.storageClass Persistent Volume storage class
          ## If defined, storageClassName: <storageClass>
          ## If set to "-", storageClassName: "", which disables dynamic provisioning
          ## If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner
          ##
          storageClass: ""
          ## @param persistence.accessModes [array] Persistent Volume access modes
          ##
          accessModes:
            - ReadWriteOnce
          ## @param persistence.accessMode Persistent Volume access mode (DEPRECATED: use `persistence.accessModes` instead)
          ##
          accessMode: ReadWriteOnce
          ## @param persistence.size Persistent Volume size
          ##
          size: 10Gi
          ## @param persistence.dataSource Custom PVC data source
          ##
          dataSource: {}
          ## @param persistence.existingClaim The name of an existing PVC to use for persistence
          ##
          existingClaim: ""
          ## @param persistence.selector Selector to match an existing Persistent Volume for WordPress data PVC
          ## If set, the PVC can't have a PV dynamically provisioned for it
          ## E.g.
          ## selector:
          ##   matchLabels:
          ##     app: my-app
          ##
          selector: {}
          ## @param persistence.annotations Persistent Volume Claim annotations
          ##
          annotations: {}
        allowEmptyPassword: false
        existingSecret: wordpress-credentials
        wordpressUsername: rubenhensen
        smtpExistingSecret: wordpress-credentials
        customHTAccessCM: prod-wordpress-cm
        resourcesPreset: "small"
        livenessProbe:
          enabled: false

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: mbgwp-helm-mariadb
      namespace: mbgwp
      jsonPointers:
      - /spec/template/spec/containers/0/livenessProbe
      - /spec/template/spec/containers/0/readinessProbe
