apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owntracks-folder
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rubenhensen/k8scd.git
    targetRevision: HEAD
    path: owntracks
  destination:
    server: https://kubernetes.default.svc
    namespace: owntracks
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true