apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sogo-mail
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  project: default
  sources:
    - chart: sogo
      repoURL: https://helm.snry.xyz/docker-sogo/
      targetRevision: 0.3.5
      helm:
        values: |
          sogo:
            host: mail.rubenhensen.nl
            image:
              tag: "5.12.5"
            existingSecrets:
              - sogo-mail-secrets
          ingress:
            enabled: true
            className: nginx
            annotations:
              kubernetes.io/tls-acme: "true"
              cert-manager.io/cluster-issuer: prod-cluster-issuer
              nginx.ingress.kubernetes.io/server-snippet: |-
                proxy_http_version 1.1;
                proxy_hide_header X-Powered-By;

                location = / {
                  rewrite ^(.*)$ /SOGo;
                  allow all;
                }

            tls:
              - secretName: sogo-mail-tls
                hosts:
                  - mail.rubenhensen.nl
            path: /
            pathType: Prefix
          memcached:
            enabled: true
            image:
              tag: latest
    - repoURL: https://github.com/rubenhensen/k8scd.git
      targetRevision: HEAD
      path: sogo-mail
      directory:
        include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: sogo-mail
