apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-ldap
data:
  ldap.yaml: |
    version: 1
    metadata:
      name: LDAP Outpost
    entries:
      - model: authentik_providers_ldap.ldapprovider
        id: ldap-provider
        state: present
        identifiers:
          name: LDAP
        attrs:
          name: LDAP
          authorization_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          base_dn: "DC=ldap,DC=goauthentik,DC=io"
          bind_mode: direct
          search_mode: direct
          mfa_support: false
