apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: kv/authentik
        property: secret_key
    - secretKey: bootstrap_password
      remoteRef:
        key: kv/authentik
        property: bootstrap_password
    - secretKey: bootstrap_token
      remoteRef:
        key: kv/authentik
        property: bootstrap_token
    - secretKey: postgres_password
      remoteRef:
        key: kv/authentik
        property: postgres_password
