apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
  - name: app
    port: 80
    targetPort: 8123
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  clusterIP: None
  type: ClusterIP