apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: helm-immich
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: server
    app.kubernetes.io/version: v1.119.0
    helm.sh/chart: immich-0.8.5
  name: helm-immich-server
  namespace: immich
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: helm-immich
        app.kubernetes.io/name: server
    spec:
      automountServiceAccountToken: true
      containers:
        - startupProbe:
            failureThreshold: 40
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          