apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: helm-immich-server
  namespace: immich
spec:
  template:
    spec:
      containers:
        - startupProbe:
            failureThreshold: 40
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          