---
nginx_server_name: "mail.rubenhensen.nl"
nginx_stalwart_server_name: "stalwart.rubenhensen.nl"
nginx_tls_cert: "/etc/letsencrypt/live/mail.rubenhensen.nl/fullchain.pem"
nginx_tls_key: "/etc/letsencrypt/live/mail.rubenhensen.nl/privkey.pem"
nginx_stalwart_backend: "127.0.0.1:8443"
nginx_sogo_backend: "127.0.0.1:20000"
