apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "stalwart.fullname" . }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: prod-cluster-issuer
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: mail.hensen.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "stalwart.fullname" . }}
            port:
              number: 8080
  - host: autoconfig.hensen.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "stalwart.fullname" . }}
            port:
              number: 8080
  - host: autodiscover.hensen.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "stalwart.fullname" . }}
            port:
              number: 8080
  tls:
    - secretName: letsencrypt-prod
      hosts:
        - mail.hensen.io
        - autoconfig.hensen.io
        - autodiscover.hensen.io
