apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true 
  project: default
  sources:
    - chart: mailu
      repoURL: https://mailu.github.io/helm-charts/
      targetRevision: 2.1.1
      helm:
        valueFiles:
          - $values/mailu/values.yaml
    - repoURL: https://github.com/rubenhensen/k8scd.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets