apiVersion: v1
kind: ConfigMap
metadata:
  name: sogo-config
  namespace: sogo
data:
  sogo.yaml: |
    # Mail Server Configuration
    SOGoIMAPServer: stalwart.stalwart.svc.cluster.local:143
    SOGoSMTPServer: stalwart.stalwart.svc.cluster.local:587
    SOGoMailDomain: hensen.io
    SOGoForceIMAPLoginWithEmail: true

    # Database Configuration
    SOGoProfileURL: "postgresql://sogo:${POSTGRES_PASSWORD}@sogo-postgres-rw.sogo.svc.cluster.local:5432/sogo/sogo_user_profile?sslmode=require"
    OCSFolderInfoURL: "postgresql://sogo:${POSTGRES_PASSWORD}@sogo-postgres-rw.sogo.svc.cluster.local:5432/sogo/sogo_folder_info?sslmode=require"
    OCSSessionsFolderURL: "postgresql://sogo:${POSTGRES_PASSWORD}@sogo-postgres-rw.sogo.svc.cluster.local:5432/sogo/sogo_sessions_folder?sslmode=require"
    OCSAclURL: "postgresql://sogo:${POSTGRES_PASSWORD}@sogo-postgres-rw.sogo.svc.cluster.local:5432/sogo/sogo_acl?sslmode=require"

    # General Settings
    SOGoTimeZone: Europe/Amsterdam
    SOGoLanguage: English
    SOGoSuperUsername: admin@hensen.io

    # Modules
    SOGoModules:
      - Mail
      - Calendar
      - Contacts
      - Tasks

    # Calendar Settings
    SOGoCalendarDefaultRoles:
      - PublicViewer
      - ConfidentialDAndTViewer
    SOGoFirstDayOfWeek: 1
    SOGoFirstWeekOfYear: January1
    SOGoDayStartTime: 8
    SOGoDayEndTime: 18

    # Authentication
    SOGoAuthenticationType: IMAP

    # WebUI Settings
    SOGoPageTitle: "SOGo @ hensen.io"
    SOGoLoginModule: Mail
    SOGoRefreshViewCheck: every_5_minutes
    SOGoMailMessageCheck: every_5_minutes

    # Mail Preferences
    SOGoMailAuxiliaryUserAccountsEnabled: true
    SOGoMailComposeMessageType: html
    SOGoMailReplyPlacement: below
    SOGoMailSignaturePlacement: below

    # Security
    SOGoPasswordChangeEnabled: false
    SOGoXSRFValidationEnabled: true

    # Performance
    SOGoMemcachedHost: ""
    WOWorkersCount: 3
    WOListenQueueSize: 5
    WONoDetach: true
    WOLogFile: "-"
    WOPidFile: /var/run/sogo/sogo.pid
