
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sogo-postgres-credentials
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: sogo-postgres-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ `{{ .postgres_user }}` }}"
        password: "{{ `{{ .postgres_pw }}` }}"
  dataFrom:
  - extract:
      key: kv/sogo

