apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sogo-config
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: sogo-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SOGoProfileURL: "postgresql://{{ .postgres_user }}:{{ .postgres_pw }}@sogo-postgres-rw:5432/sogo/sogo_user_profile?sslmode=require"
        OCSFolderInfoURL: "postgresql://{{ .postgres_user }}:{{ .postgres_pw }}@sogo-postgres-rw:5432/sogo/sogo_folder_info?sslmode=require"
        OCSSessionsFolderURL: "postgresql://{{ .postgres_user }}:{{ .postgres_pw }}@sogo-postgres-rw:5432/sogo/sogo_sessions_folder?sslmode=require"
        OCSCacheFolderURL: "postgresql://{{ .postgres_user }}:{{ .postgres_pw }}@sogo-postgres-rw:5432/sogo/sogo_cache_folder?sslmode=require"
        OCSStoreURL: "postgresql://{{ .postgres_user }}:{{ .postgres_pw }}@sogo-postgres-rw:5432/sogo/sogo_store?sslmode=require"
        OCSAclURL: "postgresql://{{ .postgres_user }}:{{ .postgres_pw }}@sogo-postgres-rw:5432/sogo/sogo_acl?sslmode=require"
        SOGoUserSources__yaml: |
          - type: imap
            id: stalwart
            canAuthenticate: YES
            isAddressBook: NO
            displayName: "Stalwart Mail"
            hostname: "stalwart.stalwart.svc.cluster.local"
            port: 993
            encryption: tls
            loginFieldNames:
              - mail
              - cn
        SOGoIMAPServer: "imaps://stalwart.stalwart.svc.cluster.local:993"
        SOGoSieveServer: "sieve://stalwart.stalwart.svc.cluster.local:4190"
        SOGoSMTPServer: "stalwart.stalwart.svc.cluster.local"
        SOGoMailDomain: "hensen.io"
        SOGoForceExternalLoginWithEmail: "YES"
  dataFrom:
  - extract:
      key: kv/sogo
