apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sogo-secrets
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: sogo-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SOGoProfileURL: "postgresql://{{ .postgres_user }}:{{ .postgres_pw }}@sogo-postgres-rw:5432/sogo/sogo_user_profile"
        OCSFolderInfoURL: "postgresql://{{ .postgres_user }}:{{ .postgres_pw }}@sogo-postgres-rw:5432/sogo/sogo_folder_info"
        OCSSessionsFolderURL: "postgresql://{{ .postgres_user }}:{{ .postgres_pw }}@sogo-postgres-rw:5432/sogo/sogo_sessions_folder"
        OCSCacheFolderURL: "postgresql://{{ .postgres_user }}:{{ .postgres_pw }}@sogo-postgres-rw:5432/sogo/sogo_cache_folder"
        OCSStoreURL: "postgresql://{{ .postgres_user }}:{{ .postgres_pw }}@sogo-postgres-rw:5432/sogo/sogo_store"
        OCSAclURL: "postgresql://{{ .postgres_user }}:{{ .postgres_pw }}@sogo-postgres-rw:5432/sogo/sogo_acl"
        SOGoUserSources__yaml: |
          - type: sql
            id: directory
            viewURL: "postgresql://{{ .postgres_user }}:{{ .postgres_pw }}@sogo-postgres-rw:5432/sogo/sogo_users"
            canAuthenticate: NO
            isAddressBook: NO
            userPasswordAlgorithm: none
        SOGoIMAPServer: "imaps://stalwart.stalwart.svc.cluster.local:993"
        SOGoSieveServer: "sieve://stalwart.stalwart.svc.cluster.local:4190"
        SOGoSMTPServer: "stalwart.stalwart.svc.cluster.local"
        SOGoMailDomain: "hensen.io"
        SOGoForceExternalLoginWithEmail: "YES"
  dataFrom:
  - extract:
      key: kv/sogo
