# additional resources like ingress rules, cluster and repository secrets.
resources:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=stable
- cmp-plugin.yaml

namespace: argocd
# changes to config maps
patches:
- path: overlays/cmp-plugin-pathc.yaml
