apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd


# additional resources like ingress rules, cluster and repository secrets.
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml?ref=stable
# - cmp-plugin.yaml

# changes to config maps
# patches:
# - path: overlays/cmp-plugin-patch.yaml
