apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd


# additional resources like ingress rules, cluster and repository secrets.
resources:
- https://github.com/argoproj/argo-cd/releases/download/v2.12.3/argocd-linux-amd64
- ingress.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: ReplicaSet
      name: argocd-notifications-controller
    path: overlays/argocd-notifications-controller-patch.yaml