apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webhook-es
  namespace: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Owner
  data:
  - secretKey: webhook.github.secret
    remoteRef:
      key: github_secret
    template:
      engine: gotmpl
      data: |
        [default]
        aws_access_key_id={{ .aws_access_key_id }}
        aws_secret_access_key={{ .aws_secret_access_key }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webhook-es
  namespace: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        webhook.github.secret: "{{ .mysecret | toString }}"
    name: argocd-secret
    creationPolicy: Owner
  data:
  - secretKey: mysecret
    remoteRef:
      key: github_secret     

      