apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snappymail-data
  labels:
    app: snappymail
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
