---
fail2ban_bantime: "1h"
fail2ban_findtime: "10m"
fail2ban_maxretry: 5

fail2ban_jails:
  - name: sshd
    enabled: true
    port: "{{ ssh_port | default(22) }}"
    maxretry: 3
    bantime: "1h"
  - name: stalwart-auth
    enabled: true
    port: "25,465,587,993,443"
    maxretry: 5
    bantime: "1h"
    logpath: "/opt/stalwart/logs/stalwart.log*"
    filter: stalwart-auth
