version: '3'

services:

  # see FAQ entry below if upgrading from a different PostgreSQL major version (e.g. 12 to 15):
  # https://tt-rss.org/wiki/InstallationNotes/#i-got-the-updated-compose-file-above-and-now-my-database-keeps-restarting
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${TTRSS_DB_USER}
      - POSTGRES_PASSWORD=${TTRSS_DB_PASS}
      - POSTGRES_DB=${TTRSS_DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data

  app:
    image: cthulhoo/ttrss-fpm-pgsql-static:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - app:/var/www/html
      - ./config.d:/opt/tt-rss/config.d:ro
    depends_on:
      - db

#  optional, makes weekly backups of your install
#  backups:
#    image: cthulhoo/ttrss-fpm-pgsql-static:latest
#    restart: unless-stopped
#    env_file:
#      - .env
#    volumes:
#      - backups:/backups
#      - app:/var/www/html
#    depends_on:
#      - db
#    command: /opt/tt-rss/dcron.sh -f

  updater:
    image: cthulhoo/ttrss-fpm-pgsql-static:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - app:/var/www/html
      - ./config.d:/opt/tt-rss/config.d:ro
    depends_on:
      - app
    command: /opt/tt-rss/updater.sh

  web-nginx:
    image: cthulhoo/ttrss-web-nginx:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - app:/var/www/html:ro
    depends_on:
      - app

volumes:
  db:
  app:
  backups:


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: sol-auth
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: sol-auth
#   template:
#     metadata:
#       labels:
#         app: sol-auth
#     spec:
#       # securityContext:
#       #     runAsUser: 1000
#       #     runAsGroup: 1000
#       #     fsGroup: 1000
#       containers:
#         - image: hebury/sol-auth:2.3
#           name: sol-auth
#           resources: 
#             requests:
#               memory: "50Mi"
#             limits:
#               memory: "500Mi"
#           ports:
#             - name: http
#               containerPort: 8002
#               hostPort: 8002
#               protocol: TCP
#           volumeMounts:
#           - name: config-volume
#             mountPath: /config/
#       volumes:
#         - name: config-volume
#           configMap:
#             name: httpd-conf
#       restartPolicy: Always
#       terminationGracePeriodSeconds: 5