apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true 
    automated:
      selfHeal: true
      prune: true
  project: default
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.28.1
    - repoURL: https://github.com/rubenhensen/k8scd
      path: vault
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/override.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-system