apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-vault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true 
  project: default
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.28.1
      helm:
        valueFiles:
        - overrides.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: vault