apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: whishper
  name: whishper
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 80
  selector:
    io.kompose.service: whishper
