apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
  annotations:
    velero.io/csi-volumesnapshot-class_driver.longhorn.io: "longhorn-backup-vsc"
spec:
  schedule: "44 21 * * *"  # Daily at 1 AM
  template:
    # includedNamespaces:
    #   - immich
    #   - nextcloud
    #   - home-assistant
    #   - ttrss
    ttl: 30d  # 30 days
    defaultVolumesToFsBackup: true
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: weekly-backup
  namespace: velero
  annotations:
    velero.io/csi-volumesnapshot-class_driver.longhorn.io: "longhorn-backup-vsc"
spec:
  schedule: "0 0 * * 0"  # Weekly on Sunday at midnight
  template:
    # includedNamespaces:
    #   - immich
    #   - nextcloud
    #   - home-assistant
    #   - ttrss
    ttl: 90d  # 90 days
    defaultVolumesToFsBackup: true