apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup2
spec:
  schedule: "*/1 * * * *"  # Daily at 1 AM
  template:
    ttl: 30d
    defaultVolumesToFsBackup: true
    snapshotVolumes: true
    snapshotMoveData: true
    includedNamespaces:
      - ttrss