apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: test-backup
  annotations:
    velero.io/csi-volumesnapshot-class_driver.longhorn.io: "longhorn-backup-vsc"
spec:
  schedule: "*/2 * * * *"  # Daily at 1 AM
  template:
    includedNamespaces:
      - ttrss
    ttl: 15m  # 30 days
    defaultVolumesToFsBackup: true
    snapshotVolumes: true
    snapshotMoveData: true