apiVersion: v1
kind: Service
metadata:
  labels:
    app: lingo
  name: lingo
spec:
  ports:
    - name: "api"
      port: 8000
      targetPort: 8000
    - name: "frontend"
      port: 8001
      targetPort: 8001
  selector:
    app: lingo
