apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true 
    automated:
      selfHeal: true
      prune: true
  project: default
  sources:
    - chart: tenant
      repoURL: https://operator.min.io
      targetRevision: 6.0.3
      helm:
        valueFiles:
          - $values/minio/values-tenant.yaml
    - repoURL: https://github.com/rubenhensen/k8scd.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: minio