apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-tenant-es
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: myminio-env-configuration
  dataFrom:
    - extract:
        key: minio-tenant-root
        property: config.env

  # # metadataPolicy to fetch all the labels in JSON format
  # - secretKey: tags
  #   remoteRef:
  #     metadataPolicy: Fetch
  #     key: foo

  # # metadataPolicy to fetch a specific label (dev) from the source secret
  # - secretKey: developer
  #   remoteRef:
  #     metadataPolicy: Fetch
  #     key: foo
  #     property: dev