tenant:
  pools:
    - servers: 1
      name: pool-0
  ingress:
    api: 
      enabled: true
      ingressClassName: nginx
      labels: { }
      annotations:     
        cert-manager.io/cluster-issuer: prod-cluster-issuer
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      tls: 
      # TLS secretName used on ClusterIssuer
      - secretName:  letsencrypt-prod
        hosts:
          - minio.hensen.io

      host: minio.hensen.io
      path: /
      pathType: Prefix
    console:
      enabled: true
      ingressClassName: nginx
      labels: { }
      annotations:     
        cert-manager.io/cluster-issuer: prod-cluster-issuer
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      tls: 
      # TLS secretName used on ClusterIssuer
      - secretName:  letsencrypt-prod
        hosts:
          - minio-console.hensen.io

      host: minio-console.hensen.io
      path: /
      pathType: Prefix