ingress:
  enabled: true
  ingressClassName: nginx
  labels: { }
  annotations:     
    cert-manager.io/cluster-issuer: prod-cluster-issuer
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  tls: 
  # TLS secretName used on ClusterIssuer
  - secretName:  letsencrypt-prod
    hosts:
      - argocd.hensen.io

  host: minio.hensen.io
  path: /
  pathType: Prefix