{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "sogo.fullname" . }}-postgres-credentials
  labels:
    {{- include "sogo.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: ClusterSecretStore
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  target:
    name: {{ include "sogo.fullname" . }}-postgres-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ `{{ .postgres_user }}` }}"
        password: "{{ `{{ .postgres_pw }}` }}"
  dataFrom:
  - extract:
      key: {{ .Values.externalSecret.vaultPath }}
{{- end }}
