apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mbgwp-mariadb-credentials
  namespace: mbgwp
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mbgwp-mariadb-credentials
    creationPolicy: Owner
  data:
    - secretKey: root-password
      remoteRef:
        key: kv/mariadboperator
        property: mariadb-operator-root-password
    - secretKey: password
      remoteRef:
        key: kv/mariadboperator
        property: mariadb-operator-user-password
    - secretKey: mariadb-password
      remoteRef:
        key: kv/mariadboperator
        property: mariadb-operator-user-password
