apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  annotations:
    velero.io/csi-volumesnapshot-class_driver.longhorn.io: "longhorn-backup-vsc"
spec:
  schedule: "0 1 * * *"  # Daily at 1 AM
  template:
    ttl: 30d
    defaultVolumesToFsBackup: true
    snapshotVolumes: true
    snapshotMoveData: true