apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ente-photos-folder
spec:
  project: default
  source:
    repoURL: https://github.com/rubenhensen/k8scd.git
    targetRevision: HEAD
    path: ente-photos
  destination:
    server: https://kubernetes.default.svc
    namespace: ente-photos
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true