apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true 
  project: default
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: 0.10.3
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets