apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hensenio-ghost-secrets
  namespace: blog
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ghost-es
    creationPolicy: Owner
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: kv/ghost
        property: ghostmsqlrootpw

    - secretKey: mysql-password
      remoteRef:
        key: kv/ghost
        property: ghostmsqlpw
        
    - secretKey: ghost-password
      remoteRef:
        key: kv/ghost
        property: ghostpw